name: killme
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.1+2

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  cached_network_image: ^3.2.3
  collection: ^1.16.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6

  flutter:
    sdk: flutter

  flutter_blurhash: ^0.7.0
  flutter_gen: ^5.1.0+1
  flutter_native_splash: ^2.2.16
  flutter_riverpod: 2.1.3
  flutter_scroll_shadow: ^1.1.0
  freezed_annotation: ^2.2.0
  graphic: ^1.0.1
  intl: ^0.18.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  retrofit: ^3.3.1
  riverpod_annotation: ^1.1.1
  rustic: ^0.4.0
  shared_preferences: ^2.0.15
  sign_in_button: ^3.1.0

  # stock_mvp_api: 0.0.1
  
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.1

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.1.0+1
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.0
  
  flutter_test:
    sdk: flutter

  freezed: ^2.3.2
  retrofit_generator: ^4.2.0
  riverpod_generator: ^1.1.1

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
